export const theadData = [
  {
    title: "Date",
  },
  {
    title: "Title",
  },
  {
    title: "Topic",
    children: [
      "General Support",
      "Report an Order",
      "Account Issues",
      "Technical issues",
    ],
  },
  {
    title: "Status",
    children: ["All", "Progressing", "Solved"],
  },
];
export const myReportListData = [
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "progressing",
  },
];
