export const theadData = [
  {
    title: "Date",
  },
  {
    title: "Title",
  },
  {
    title: "Topic",
    children: [
      "General Support",
      "Report an Order",
      "Account Issues",
      "Technical issues",
    ],
  },
  {
    title: "Status",
    children: ["All", "In Progress", "Solved"],
  },
];
export const myReportListData = [
  {
    date: "02.02.2020 PM 04:44",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Technical Issues",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Technical Issues",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "Report an order",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Report an order",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "Report an order",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Report an order",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Report an order",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "Report an order",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "Report an order",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Report an order",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "Account Issues",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "02.02.2020 PM 04:44",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "Technical Issues",
    status: "In Progress",
  },
];
