export const theadData = [
  {
    title: "Date",
  },
  {
    title: "Title",
  },
  {
    title: "Topic",
    children: [
      "All",
      "General Support",
      "Report an Order",
      "Account Issues",
      "Technical issues",
    ],
  },
  {
    title: "Status",
    children: ["All", "In Progress", "Solved"],
  },
];

export const tHeadAdminData = [
  {
    title: "Date",
  },
  {
    title: "Title",
  },
  {
    title: "Requestor",
  },
  {
    title: "Requestor ID",
  },

  {
    title: "Topic",
    children: [
      "All",
      "General Support",
      "Report an Order",
      "Account Issues",
      "Technical issues",
    ],
  },
  {
    title: "Status",
    children: ["All", "In Progress", "Solved"],
  },
];

export const myReportListData = [
  {
    date: "May 6 2022 11:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Technical Issues",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Technical Issues",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "Report an order",
    orderNumber: "Order #123",
    status: "In Progress",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Report an order",
    orderNumber: "Order #123",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "Report an order",
    orderNumber: "Order#125",
    status: "In Progress",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Report an order",
    orderNumber: "Order#125",
    status: "solved",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Report an order",
    orderNumber: "Order#121",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "Report an order",
    orderNumber: "Order#121",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "Report an order",
    orderNumber: "Order #123",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    topic: "Report an order",
    orderNumber: "Order #123",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "Account Issues",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    topic: "Technical Issues",
    status: "In Progress",
  },
];

export const adminReportListData = [
  {
    date: "May 6 2022 11:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "Technical Issues",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "Technical Issues",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "Lee.S.C",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "Lee.S.C",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "Lee.S.C",
    requestorID: "12354",
    topic: "Report an order",
    orderNumber: "Order #123",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "Lee.S.C",
    requestorID: "12354",
    topic: "Report an order",
    orderNumber: "Order #126",
    status: "In Progress",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "Lee.S.C",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "Lee.G.J",
    requestorID: "12354",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "Lee.G.J",
    requestorID: "12354",
    topic: "Report an order",
    orderNumber: "Order #126",
    status: "solved",
  },
  {
    date: "May 6 2022 11:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "Report an order",
    orderNumber: "Order #121",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "Lee.G.J",
    requestorID: "12354",
    topic: "Report an order",
    orderNumber: "Order #123",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "Lee.G.J",
    requestorID: "12354",
    topic: "Report an order",
    orderNumber: "Order #123",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "quia dolor sit amet, consectetur, ",
    requestor: "Lee.G.J",
    requestorID: "12354",
    topic: "Report an order",
    orderNumber: "Order #121",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "Account Issues",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "solved",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    requestor: "Lee.G.J",
    requestorID: "12354",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Lorem Ipsum Dolor",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "General Support",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "Account Issues",
    status: "In Progress",
  },
  {
    date: "Mar 12 2012 10:00:00 AM",
    title: "Neque porro quisquam est qui dolorem ",
    requestor: "John Doe",
    requestorID: "12354",
    topic: "Technical Issues",
    status: "In Progress",
  },
];
